apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: k8s
  labels:
    run: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /metal
      name: metal-dir
  volumes:
  - name: metal-dir
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
