apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-pv
  namespace: k8s
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /opt/dados
    server: 192.168.100.200
    readOnly: false
